spring:
  application:
    name: poste
  datasource:
    url: jdbc:h2:mem:poste
  h2:
    console:
      enabled: true
  config:
    import: optional:configserver:http://config-service:9999

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"