spring:
  application:
    name: poste
  datasource:
    url: jdbc:h2:mem:poste
  h2:
    console:
      enabled: true
  config:
    import: optional:configserver:http://localhost:9999

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"